# Generated by Django 4.2.17 on 2024-12-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_bet_placed", models.DateTimeField()),
                ("payout", models.BigIntegerField()),
                ("net_pl", models.BigIntegerField()),
                ("odds", models.IntegerField()),
                ("amount_bet", models.BigIntegerField()),
                ("team_for", models.TextField()),
                ("team_against", models.TextField()),
                ("bet_placed", models.TextField()),
            ],
        ),
    ]
