# Generated by Django 4.2.17 on 2024-12-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="content", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="post", name="title", field=models.TextField(null=True),
        ),
    ]
