# Generated by Django 4.2.17 on 2024-12-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_post_content_alter_post_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="net_pl",),
    ]
